apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-restrict-capabilities
  namespace: default
spec:
  severity: 8
  selector:
    matchLabels:
      app: wisecow
  capabilities:
    matchCapabilities:
    # Block dangerous capabilities
    - capability: net_raw
    - capability: sys_admin
    - capability: sys_ptrace
    - capability: sys_module
    - capability: dac_override
    - capability: dac_read_search
    - capability: chown
    - capability: setuid
    - capability: setgid
  
  action: Block
