
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-restrict-file-access
  namespace: default
spec:
  severity: 7
  selector:
    matchLabels:
      app: wisecow
  file:
    matchDirectories:
    # Block write access to system configuration directories
    - dir: /etc/
      recursive: true
      fromSource:
      - path: /bin/sh
      - path: /bin/bash
    
    # Block write access to system binaries
    - dir: /bin/
      recursive: true
    
    - dir: /sbin/
      recursive: true
    
    - dir: /usr/bin/
      recursive: true
    
    - dir: /usr/sbin/
      recursive: true
    
    # Block write access to tmp (prevent malware staging)
    - dir: /tmp/
      recursive: true
    
    matchPaths:
    # Block access to sensitive system files
    - path: /etc/passwd
    - path: /etc/shadow
    - path: /etc/sudoers
    - path: /etc/ssh/sshd_config
    
  action: Block
