apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-restrict-process-execution
  namespace: default
spec:
  severity: 5
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
    # Block all shell interpreters
    - path: /bin/sh
    - path: /bin/bash
    - path: /bin/dash
    - path: /usr/bin/sh
    - path: /usr/bin/bash
    
    # Block command execution utilities
    - path: /usr/bin/wget
    - path: /usr/bin/curl
    - path: /bin/nc
    - path: /bin/netcat
    
    # Block package managers (prevent malware installation)
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
    - path: /usr/bin/yum
    - path: /usr/bin/dpkg
    
    # Block privilege escalation tools
    - path: /usr/bin/sudo
    - path: /bin/su
    
  action: Block
